import express from 'express';
import { getFavorites, addFavorite, removeFavorite, checkFavorite } from '../controllers/favoriteController.js';
import { authenticate } from '../middleware/auth.js';
const router = express.Router();
router.use(authenticate);
router.get('/', getFavorites);
router.post('/', addFavorite);
router.get('/check/:recipeId', checkFavorite);
router.delete('/:recipeId', removeFavorite);
export default router;
