import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Recipe from './models/Recipe.js';

dotenv.config();

const recipes = [
  {
    title: 'Classic Spaghetti Carbonara',
    description: 'A rich and creamy Italian pasta dish made with eggs, Pecorino Romano cheese, pancetta, and black pepper. No cream needed — just perfectly emulsified eggs and cheese.',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80',
    cuisine: 'Italian',
    category: 'Main Course',
    dietType: [],
    ingredients: [
      { name: 'Spaghetti', amount: '400', unit: 'g' },
      { name: 'Pancetta or guanciale', amount: '150', unit: 'g' },
      { name: 'Eggs', amount: '4', unit: 'whole' },
      { name: 'Pecorino Romano cheese', amount: '100', unit: 'g' },
      { name: 'Black pepper', amount: '2', unit: 'tsp' },
      { name: 'Salt', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      'Bring a large pot of salted water to a boil and cook spaghetti until al dente (1 minute less than package instructions).',
      'While pasta cooks, cut pancetta into small cubes. Fry in a large pan over medium heat until crispy and golden. Remove from heat.',
      'In a bowl, whisk together 3 whole eggs + 1 yolk. Add grated Pecorino Romano and a generous amount of freshly cracked black pepper. Mix well.',
      'Reserve 1 cup of pasta cooking water before draining. Drain pasta and immediately add to the pan with pancetta (off heat).',
      'Add the egg-cheese mixture to the pasta, tossing quickly. Add pasta water a splash at a time to create a silky, creamy sauce. The residual heat cooks the eggs without scrambling them.',
      'Serve immediately with extra Pecorino and black pepper on top.',
    ],
    cookingTime: 20,
    prepTime: 10,
    servings: 4,
    difficulty: 'medium',
    nutrition: { calories: 620, protein: 28, carbs: 72, fat: 24, fiber: 3, sugar: 2 },
    tags: ['pasta', 'italian', 'quick', 'dinner'],
    source: 'ai',
  },
  {
    title: 'Butter Chicken (Murgh Makhani)',
    description: 'The iconic Indian curry — tender chicken pieces in a velvety, spiced tomato-cream sauce. Mild yet deeply flavourful, best served with naan or basmati rice.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80',
    cuisine: 'Indian',
    category: 'Main Course',
    dietType: ['gluten-free'],
    ingredients: [
      { name: 'Chicken thighs (boneless)', amount: '700', unit: 'g' },
      { name: 'Plain yogurt', amount: '1/2', unit: 'cup' },
      { name: 'Butter', amount: '3', unit: 'tbsp' },
      { name: 'Heavy cream', amount: '1/2', unit: 'cup' },
      { name: 'Crushed tomatoes', amount: '400', unit: 'g' },
      { name: 'Onion (large)', amount: '1', unit: 'whole' },
      { name: 'Garlic cloves', amount: '5', unit: 'cloves' },
      { name: 'Ginger', amount: '1', unit: 'inch' },
      { name: 'Garam masala', amount: '2', unit: 'tsp' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
      { name: 'Chilli powder', amount: '1', unit: 'tsp' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
    ],
    steps: [
      'Marinate chicken: combine yogurt, 1 tsp garam masala, 1/2 tsp turmeric, chilli powder, and salt. Coat chicken and marinate for at least 30 minutes (or overnight).',
      'Grill or pan-fry marinated chicken over high heat until slightly charred on the outside. Set aside.',
      'In a large pan, melt butter over medium heat. Add diced onion and cook until golden, about 10 minutes.',
      'Add minced garlic and grated ginger. Cook 2 minutes until fragrant.',
      'Add crushed tomatoes, remaining garam masala, and cumin. Simmer for 15 minutes until sauce thickens.',
      'Blend the sauce until smooth using an immersion blender or regular blender.',
      'Return sauce to pan. Add cream and cooked chicken. Simmer 10 more minutes.',
      'Serve hot with naan or basmati rice. Garnish with cream swirl and fresh coriander.',
    ],
    cookingTime: 40,
    prepTime: 30,
    servings: 4,
    difficulty: 'medium',
    nutrition: { calories: 520, protein: 38, carbs: 14, fat: 34, fiber: 3, sugar: 8 },
    tags: ['indian', 'curry', 'chicken', 'gluten-free', 'dinner'],
    source: 'ai',
  },
  {
    title: 'Avocado Toast with Poached Egg',
    description: 'A trendy, nutritious breakfast featuring creamy smashed avocado on toasted sourdough topped with a perfectly poached egg, red pepper flakes, and lemon zest.',
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=800&q=80',
    cuisine: 'American',
    category: 'Breakfast',
    dietType: ['vegetarian'],
    ingredients: [
      { name: 'Sourdough bread', amount: '2', unit: 'slices' },
      { name: 'Ripe avocado', amount: '1', unit: 'whole' },
      { name: 'Eggs', amount: '2', unit: 'whole' },
      { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
      { name: 'Red pepper flakes', amount: '1/4', unit: 'tsp' },
      { name: 'White vinegar', amount: '1', unit: 'tbsp' },
      { name: 'Salt and black pepper', amount: '1', unit: 'pinch' },
      { name: 'Fresh chives', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      'Toast sourdough slices until golden and crispy.',
      'Halve the avocado, remove stone, and scoop flesh into a bowl. Add lemon juice, salt, and pepper. Mash with a fork to desired consistency (chunky or smooth).',
      'Bring a small saucepan of water to a gentle simmer. Add white vinegar.',
      'Crack each egg into a small cup. Create a gentle whirlpool in the water and slide egg in. Poach for 3 minutes for a runny yolk.',
      'Spread smashed avocado generously over each toast slice.',
      'Top each with a poached egg. Sprinkle red pepper flakes, fresh chives, and a pinch of flaky salt.',
      'Serve immediately.',
    ],
    cookingTime: 10,
    prepTime: 5,
    servings: 2,
    difficulty: 'easy',
    nutrition: { calories: 380, protein: 16, carbs: 32, fat: 22, fiber: 8, sugar: 2 },
    tags: ['breakfast', 'vegetarian', 'healthy', 'quick', 'egg'],
    source: 'ai',
  },
  {
    title: 'Authentic Chicken Biryani',
    description: 'A fragrant and royal Indian dish with layers of marinated chicken, basmati rice, caramelized onions, and aromatic spices like saffron and cardamom.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    cuisine: 'Indian',
    category: 'Main Course',
    dietType: ['gluten-free'],
    ingredients: [
      { name: 'Basmati rice', amount: '2', unit: 'cups' },
      { name: 'Chicken (bone-in)', amount: '800', unit: 'g' },
      { name: 'Onions (thinly sliced)', amount: '3', unit: 'large' },
      { name: 'Plain yogurt', amount: '1/2', unit: 'cup' },
      { name: 'Ginger garlic paste', amount: '2', unit: 'tbsp' },
      { name: 'Biryani masala', amount: '2', unit: 'tbsp' },
      { name: 'Fresh mint leaves', amount: '1/2', unit: 'cup' },
      { name: 'Fresh coriander', amount: '1/2', unit: 'cup' },
      { name: 'Saffron milk', amount: '1/4', unit: 'cup' },
      { name: 'Ghee', amount: '4', unit: 'tbsp' },
      { name: 'Whole spices (cardamom, cloves, cinnamon, bay leaf)', amount: '1', unit: 'tbsp' },
      { name: 'Salt', amount: '2', unit: 'tsp' },
    ],
    steps: [
      'Wash basmati rice until water runs clear, then soak in water for 30 minutes. Drain.',
      'Marinate chicken with yogurt, ginger garlic paste, half the biryani masala, chopped mint, coriander, and 1 tsp salt. Set aside for 1 hour.',
      'In a large heavy-bottomed pot, heat ghee. Fry sliced onions until golden brown and crispy (birista). Remove half the onions and set aside.',
      'In the same pot, add whole spices. Then add marinated chicken and cook for 10 minutes until partially cooked.',
      'Meanwhile, boil 6 cups of water with 1 tsp salt and whole spices. Add soaked rice and cook until 70% done (about 5-6 minutes). Drain the rice.',
      'Layer the partially cooked rice over the chicken in the pot. Sprinkle the reserved fried onions, remaining mint, coriander, and biryani masala on top.',
      'Pour the saffron milk and a tablespoon of ghee evenly over the rice layer.',
      'Cover the pot tightly with a lid (seal with foil to trap steam). Cook on very low heat (dum) for 20-25 minutes.',
      'Turn off the heat and let it rest for 10 minutes before gently fluffing and serving with raita.',
    ],
    cookingTime: 45,
    prepTime: 20,
    servings: 6,
    difficulty: 'hard',
    nutrition: { calories: 650, protein: 35, carbs: 55, fat: 25, fiber: 4, sugar: 5 },
    tags: ['indian', 'biryani', 'chicken', 'gluten-free', 'dinner', 'rice'],
    source: 'ai',
  },
  {
    title: 'Chicken Fried Rice',
    description: 'A quick and satisfying Chinese-style fried rice with tender chicken, vegetables, and a savoury soy-sesame sauce. Perfect for using up leftover rice.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    cuisine: 'Chinese',
    category: 'Main Course',
    dietType: [],
    ingredients: [
      { name: 'Cooked rice (day-old)', amount: '3', unit: 'cups' },
      { name: 'Chicken breast (diced)', amount: '300', unit: 'g' },
      { name: 'Eggs', amount: '3', unit: 'whole' },
      { name: 'Frozen mixed vegetables', amount: '1', unit: 'cup' },
      { name: 'Spring onions', amount: '4', unit: 'stalks' },
      { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '1', unit: 'tsp' },
      { name: 'Garlic cloves', amount: '4', unit: 'cloves' },
      { name: 'Ginger', amount: '1', unit: 'tsp' },
      { name: 'Vegetable oil', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat a wok or large pan over very high heat until smoking. Add oil.',
      'Season diced chicken with salt. Stir-fry for 4–5 minutes until cooked through. Remove and set aside.',
      'Add garlic and ginger to the wok. Stir-fry 30 seconds.',
      'Add frozen vegetables and stir-fry 2 minutes.',
      'Push everything to the sides. Crack eggs into the centre and scramble until just cooked.',
      'Add day-old rice (break up any clumps). Toss everything together over high heat for 3 minutes.',
      'Add cooked chicken back in. Pour soy sauce and sesame oil around the edges of the pan. Toss well.',
      'Garnish with sliced spring onions. Serve immediately.',
    ],
    cookingTime: 15,
    prepTime: 10,
    servings: 4,
    difficulty: 'easy',
    nutrition: { calories: 450, protein: 30, carbs: 52, fat: 12, fiber: 4, sugar: 3 },
    tags: ['chinese', 'rice', 'chicken', 'quick', 'dinner', 'stir-fry'],
    source: 'ai',
  },
  {
    title: 'Greek Salad (Horiatiki)',
    description: 'A refreshing, classic Greek salad with ripe tomatoes, cucumber, Kalamata olives, red onion, and a generous slab of feta cheese. Dressed with extra virgin olive oil.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80',
    cuisine: 'Mediterranean',
    category: 'Salad',
    dietType: ['vegetarian', 'gluten-free'],
    ingredients: [
      { name: 'Large ripe tomatoes', amount: '3', unit: 'whole' },
      { name: 'Cucumber', amount: '1', unit: 'large' },
      { name: 'Red onion', amount: '1/2', unit: 'medium' },
      { name: 'Kalamata olives', amount: '1/2', unit: 'cup' },
      { name: 'Feta cheese (block)', amount: '200', unit: 'g' },
      { name: 'Green pepper', amount: '1', unit: 'whole' },
      { name: 'Extra virgin olive oil', amount: '4', unit: 'tbsp' },
      { name: 'Dried oregano', amount: '1', unit: 'tsp' },
      { name: 'Salt and pepper', amount: '1', unit: 'pinch' },
    ],
    steps: [
      'Cut tomatoes into chunky wedges and place in a large bowl.',
      'Slice cucumber into half-moons. Add to bowl.',
      'Thinly slice red onion into rings. Add to bowl.',
      'Slice green pepper into rings. Add along with Kalamata olives.',
      'Place a whole slab of feta cheese on top (traditional) or crumble it over.',
      'Drizzle generously with extra virgin olive oil.',
      'Sprinkle with dried oregano, salt, and black pepper.',
      'Serve immediately at room temperature. Do not toss — mix gently at the table.',
    ],
    cookingTime: 0,
    prepTime: 10,
    servings: 4,
    difficulty: 'easy',
    nutrition: { calories: 280, protein: 9, carbs: 12, fat: 22, fiber: 3, sugar: 7 },
    tags: ['salad', 'mediterranean', 'vegetarian', 'gluten-free', 'healthy', 'no-cook'],
    source: 'ai',
  },
  {
    title: 'Japanese Miso Soup',
    description: 'A comforting, deeply umami Japanese soup made with dashi broth, white miso paste, silken tofu, and wakame seaweed. Ready in 10 minutes.',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    cuisine: 'Japanese',
    category: 'Soup',
    dietType: ['vegetarian', 'vegan'],
    ingredients: [
      { name: 'White miso paste', amount: '3', unit: 'tbsp' },
      { name: 'Silken tofu', amount: '200', unit: 'g' },
      { name: 'Dried wakame seaweed', amount: '2', unit: 'tsp' },
      { name: 'Dashi stock or vegetable broth', amount: '4', unit: 'cups' },
      { name: 'Spring onions', amount: '3', unit: 'stalks' },
    ],
    steps: [
      'Rehydrate dried wakame in cold water for 5 minutes. Drain and set aside.',
      'Heat dashi stock in a medium saucepan over medium heat until just below boiling. Do NOT boil miso soup.',
      'Cut silken tofu into small 1cm cubes. Add to the warm broth along with drained wakame.',
      'Place miso paste in a small strainer or ladle. Dip into the broth and stir gently to dissolve without leaving lumps.',
      'Heat gently for 1–2 more minutes. Do not let it boil.',
      'Ladle into bowls and top with thinly sliced spring onions. Serve immediately.',
    ],
    cookingTime: 10,
    prepTime: 5,
    servings: 4,
    difficulty: 'easy',
    nutrition: { calories: 85, protein: 6, carbs: 8, fat: 3, fiber: 1, sugar: 2 },
    tags: ['japanese', 'soup', 'vegetarian', 'vegan', 'quick', 'healthy'],
    source: 'ai',
  },
  {
    title: 'Chocolate Lava Cake',
    description: 'Decadent individual chocolate cakes with a warm, gooey molten centre. Surprisingly easy to make and guaranteed to impress. Serve with vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&q=80',
    cuisine: 'American',
    category: 'Dessert',
    dietType: ['vegetarian'],
    ingredients: [
      { name: 'Dark chocolate (70%)', amount: '150', unit: 'g' },
      { name: 'Unsalted butter', amount: '100', unit: 'g' },
      { name: 'Eggs', amount: '3', unit: 'whole' },
      { name: 'Egg yolks', amount: '2', unit: 'yolks' },
      { name: 'Caster sugar', amount: '80', unit: 'g' },
      { name: 'Plain flour', amount: '2', unit: 'tbsp' },
      { name: 'Cocoa powder (for dusting)', amount: '1', unit: 'tbsp' },
      { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
      { name: 'Pinch of salt', amount: '1', unit: 'pinch' },
    ],
    steps: [
      'Preheat oven to 200°C (390°F). Grease 4 ramekins well with butter and dust with cocoa powder.',
      'Melt dark chocolate and butter together in a heatproof bowl over simmering water (double boiler), stirring until smooth. Remove from heat and cool slightly.',
      'In a bowl, whisk together eggs, egg yolks, and sugar until pale and slightly thick, about 3 minutes.',
      'Fold the chocolate mixture into the egg mixture. Add vanilla and pinch of salt. Sift in flour and fold gently until just combined.',
      'Pour the batter equally into the prepared ramekins. At this point, you can refrigerate for up to 24 hours.',
      'Bake at 200°C for exactly 12 minutes. The edges should be set but the centre should still wobble.',
      'Let sit for 1 minute. Run a knife around the edge and invert onto a plate.',
      'Serve immediately with a scoop of vanilla ice cream or a dusting of icing sugar.',
    ],
    cookingTime: 12,
    prepTime: 20,
    servings: 4,
    difficulty: 'medium',
    nutrition: { calories: 420, protein: 8, carbs: 38, fat: 28, fiber: 3, sugar: 30 },
    tags: ['dessert', 'chocolate', 'vegetarian', 'baking', 'romantic'],
    source: 'ai',
  },
  {
    title: 'Palak Paneer (Spinach & Cottage Cheese Curry)',
    description: 'A creamy, vibrant North Indian curry made with fresh spinach purée and cubes of paneer. Rich in iron and protein, it\'s a beloved vegetarian comfort food.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    cuisine: 'Indian',
    category: 'Main Course',
    dietType: ['vegetarian', 'gluten-free'],
    ingredients: [
      { name: 'Fresh spinach', amount: '500', unit: 'g' },
      { name: 'Paneer', amount: '250', unit: 'g' },
      { name: 'Onion', amount: '1', unit: 'large' },
      { name: 'Tomatoes', amount: '2', unit: 'medium' },
      { name: 'Garlic cloves', amount: '4', unit: 'cloves' },
      { name: 'Ginger', amount: '1', unit: 'inch' },
      { name: 'Heavy cream', amount: '3', unit: 'tbsp' },
      { name: 'Ghee or oil', amount: '2', unit: 'tbsp' },
      { name: 'Cumin seeds', amount: '1', unit: 'tsp' },
      { name: 'Garam masala', amount: '1', unit: 'tsp' },
      { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
    ],
    steps: [
      'Blanch spinach: dip in boiling water for 2 minutes, then immediately into ice water. This preserves the bright green colour.',
      'Blend blanched spinach with 2 tbsp water until smooth. Set aside.',
      'Cut paneer into cubes. Shallow-fry in ghee until golden on all sides. Set aside.',
      'In the same pan, add remaining ghee and cumin seeds. Let them splutter.',
      'Add diced onion and cook until golden, about 8 minutes. Add garlic and ginger paste. Cook 2 minutes.',
      'Add chopped tomatoes, turmeric, and garam masala. Cook until tomatoes break down, about 5 minutes.',
      'Add spinach purée. Stir and simmer for 5 minutes.',
      'Add fried paneer cubes and cream. Stir gently and simmer 3 more minutes.',
      'Serve with naan, roti, or steamed basmati rice.',
    ],
    cookingTime: 30,
    prepTime: 15,
    servings: 4,
    difficulty: 'medium',
    nutrition: { calories: 380, protein: 20, carbs: 12, fat: 28, fiber: 4, sugar: 4 },
    tags: ['indian', 'vegetarian', 'gluten-free', 'curry', 'dinner', 'healthy'],
    source: 'ai',
  },
  {
    title: 'Classic Margherita Pizza',
    description: 'The timeless Neapolitan pizza — a thin, crispy crust topped with San Marzano tomato sauce, fresh mozzarella, and basil leaves. Simple ingredients, extraordinary flavour.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80',
    cuisine: 'Italian',
    category: 'Main Course',
    dietType: ['vegetarian'],
    ingredients: [
      { name: 'Pizza dough (store-bought or homemade)', amount: '400', unit: 'g' },
      { name: 'San Marzano tomatoes (canned)', amount: '400', unit: 'g' },
      { name: 'Fresh mozzarella', amount: '200', unit: 'g' },
      { name: 'Fresh basil leaves', amount: '10', unit: 'leaves' },
      { name: 'Extra virgin olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Garlic clove', amount: '1', unit: 'clove' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to maximum temperature (250°C / 480°F). Place a baking stone or heavy baking tray inside to heat up.',
      'Make the sauce: crush canned tomatoes by hand. Mix with a pinch of salt and 1 tbsp olive oil. Do not cook.',
      'Stretch the pizza dough on a floured surface into a thin circle about 30cm in diameter.',
      'Spread a thin layer of tomato sauce over the base, leaving a 1cm border.',
      'Tear mozzarella into pieces and scatter evenly over the sauce.',
      'Slide pizza onto the preheated stone/tray. Bake for 8–10 minutes until crust is golden and cheese is bubbly with some char.',
      'Remove from oven. Immediately top with fresh basil leaves and a drizzle of olive oil.',
      'Slice and serve at once.',
    ],
    cookingTime: 10,
    prepTime: 20,
    servings: 2,
    difficulty: 'medium',
    nutrition: { calories: 560, protein: 22, carbs: 68, fat: 20, fiber: 4, sugar: 6 },
    tags: ['italian', 'pizza', 'vegetarian', 'baking', 'dinner'],
    source: 'ai',
  },
  {
    title: 'Thai Green Curry',
    description: 'An aromatic, coconut-based Thai curry with tender chicken, vegetables, and fragrant green curry paste. Creamy, spicy, and ready in 30 minutes.',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
    cuisine: 'Thai',
    category: 'Main Course',
    dietType: ['gluten-free'],
    ingredients: [
      { name: 'Chicken thighs (boneless)', amount: '500', unit: 'g' },
      { name: 'Coconut milk (full fat)', amount: '400', unit: 'ml' },
      { name: 'Green curry paste', amount: '3', unit: 'tbsp' },
      { name: 'Fish sauce', amount: '2', unit: 'tbsp' },
      { name: 'Palm sugar or brown sugar', amount: '1', unit: 'tbsp' },
      { name: 'Kaffir lime leaves', amount: '4', unit: 'leaves' },
      { name: 'Thai basil', amount: '1/2', unit: 'cup' },
      { name: 'Zucchini', amount: '1', unit: 'medium' },
      { name: 'Bell pepper', amount: '1', unit: 'whole' },
      { name: 'Vegetable oil', amount: '1', unit: 'tbsp' },
      { name: 'Jasmine rice (to serve)', amount: '2', unit: 'cups' },
    ],
    steps: [
      'Start jasmine rice according to package instructions.',
      'Heat oil in a wok over medium-high heat. Add green curry paste and stir-fry for 1–2 minutes until fragrant.',
      'Add thick coconut cream (the top of the can). Cook, stirring, for 2 minutes until it starts to split.',
      'Add chicken pieces and cook until sealed on all sides, about 3 minutes.',
      'Pour in remaining coconut milk. Add kaffir lime leaves, fish sauce, and sugar. Stir well.',
      'Add sliced zucchini and bell pepper. Simmer 10–12 minutes until chicken is cooked through and vegetables are tender.',
      'Taste and adjust seasoning — more fish sauce for saltiness, sugar for sweetness.',
      'Turn off heat. Stir in Thai basil leaves.',
      'Serve over jasmine rice.',
    ],
    cookingTime: 25,
    prepTime: 10,
    servings: 4,
    difficulty: 'medium',
    nutrition: { calories: 520, protein: 32, carbs: 38, fat: 26, fiber: 4, sugar: 8 },
    tags: ['thai', 'curry', 'chicken', 'gluten-free', 'dinner', 'spicy'],
    source: 'ai',
  },
  {
    title: 'Banana Pancakes',
    description: 'Fluffy, golden American-style pancakes with ripe banana mashed into the batter. Naturally sweet and delicious served with maple syrup and fresh berries.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    cuisine: 'American',
    category: 'Breakfast',
    dietType: ['vegetarian'],
    ingredients: [
      { name: 'Ripe bananas', amount: '2', unit: 'whole' },
      { name: 'Plain flour', amount: '1.5', unit: 'cups' },
      { name: 'Milk', amount: '1', unit: 'cup' },
      { name: 'Eggs', amount: '2', unit: 'whole' },
      { name: 'Baking powder', amount: '2', unit: 'tsp' },
      { name: 'Sugar', amount: '2', unit: 'tbsp' },
      { name: 'Butter (melted)', amount: '2', unit: 'tbsp' },
      { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
      { name: 'Pinch of salt', amount: '1', unit: 'pinch' },
      { name: 'Maple syrup (to serve)', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      'Mash ripe bananas in a large bowl until smooth.',
      'Add eggs, milk, melted butter, and vanilla. Whisk together.',
      'Sift in flour, baking powder, sugar, and salt. Stir gently until just combined — small lumps are fine. Do not overmix.',
      'Let batter rest for 5 minutes.',
      'Heat a non-stick pan over medium heat. Lightly grease with butter.',
      'Pour about 1/4 cup batter per pancake. Cook until bubbles form on the surface and edges look set, about 2–3 minutes.',
      'Flip and cook another 1–2 minutes until golden.',
      'Stack and serve with maple syrup, sliced banana, and fresh berries.',
    ],
    cookingTime: 15,
    prepTime: 10,
    servings: 4,
    difficulty: 'easy',
    nutrition: { calories: 320, protein: 10, carbs: 58, fat: 7, fiber: 3, sugar: 18 },
    tags: ['breakfast', 'vegetarian', 'pancakes', 'banana', 'sweet', 'easy'],
    source: 'ai',
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB connected');

    // Check if recipes already exist
    const existingCount = await Recipe.countDocuments({ source: 'ai', createdBy: { $exists: false } });
    if (existingCount >= 10) {
      console.log(`ℹ️  ${existingCount} seed recipes already exist. Skipping seed.`);
      process.exit(0);
    }

    // Clear old seed recipes (without a createdBy) and re-seed
    await Recipe.deleteMany({ source: 'ai', createdBy: { $exists: false } });
    console.log('🗑️  Old seed recipes cleared');

    const inserted = await Recipe.insertMany(recipes);
    console.log(`✅ Successfully seeded ${inserted.length} recipes!`);
    inserted.forEach(r => console.log(`   - ${r.title}`));

    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
