import jsPDF from 'jspdf';

/**
 * Export a recipe as a formatted PDF
 */
export const exportRecipePDF = (recipe) => {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  let y = 20;

  const addText = (text, x, size = 12, style = 'normal', color = [0, 0, 0]) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, pageW - x - 20);
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, x, y);
      y += size * 0.5;
    });
    y += 3;
  };

  // Header
  doc.setFillColor(249, 115, 22);
  doc.rect(0, 0, pageW, 14, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('RecipeIQ – Cook Smarter with AI', 15, 9);
  y = 22;

  // Title
  addText(recipe.title, 15, 22, 'bold', [30, 30, 30]);
  addText(recipe.description || '', 15, 11, 'normal', [100, 100, 100]);
  y += 2;

  // Meta row
  const meta = [
    `🕐 ${recipe.cookingTime || 0} min cook`,
    `👥 ${recipe.servings || 4} servings`,
    `🔥 ${recipe.nutrition?.calories || 0} kcal`,
    `📊 ${recipe.difficulty || 'easy'}`,
  ].join('    ');
  addText(meta, 15, 10, 'normal', [80, 80, 80]);
  y += 4;

  // Ingredients
  addText('Ingredients', 15, 14, 'bold', [249, 115, 22]);
  (recipe.ingredients || []).forEach(ing => {
    addText(`• ${ing.amount || ''} ${ing.unit || ''} ${ing.name}`.trim(), 20, 11);
  });
  y += 4;

  // Steps
  addText('Instructions', 15, 14, 'bold', [249, 115, 22]);
  (recipe.steps || []).forEach((step, i) => {
    addText(`${i + 1}. ${step}`, 20, 11);
    y += 1;
  });
  y += 4;

  // Nutrition
  if (recipe.nutrition) {
    addText('Nutrition Per Serving', 15, 14, 'bold', [249, 115, 22]);
    const { calories, protein, carbs, fat, fiber, sugar } = recipe.nutrition;
    const nutStr = [
      `Calories: ${calories || 0} kcal`,
      `Protein: ${protein || 0}g`,
      `Carbs: ${carbs || 0}g`,
      `Fat: ${fat || 0}g`,
      `Fiber: ${fiber || 0}g`,
      `Sugar: ${sugar || 0}g`,
    ].join('  |  ');
    addText(nutStr, 15, 10, 'normal', [60, 60, 60]);
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text(`Generated by RecipeIQ · ${new Date().toLocaleDateString()} · Page ${i} of ${pageCount}`, 15, 290);
  }

  doc.save(`${recipe.title.replace(/\s+/g, '_')}_recipe.pdf`);
};
