import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ShoppingCart, Plus, X, Check, Download, Trash2 } from 'lucide-react';
import { groceryAPI } from '../../services/api.js';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';

const CATEGORIES = ['Produce', 'Meat & Seafood', 'Dairy', 'Grains & Bread', 'Canned Goods', 'Frozen', 'Beverages', 'Spices', 'Other'];

export default function GroceryPage() {
  const [lists, setLists] = useState([]);
  const [activeList, setActiveList] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showNew, setShowNew] = useState(false);
  const [newListName, setNewListName] = useState('');
  const [newItem, setNewItem] = useState({ name: '', amount: '', unit: '', category: 'Other' });
  const [showAddItem, setShowAddItem] = useState(false);

  useEffect(() => {
    groceryAPI.getAll().then(d => {
      setLists(d.lists || []);
      if (d.lists?.length > 0) loadList(d.lists[0]._id);
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const loadList = async (id) => {
    try {
      const { list } = await groceryAPI.getById(id);
      setActiveList(list);
    } catch {}
  };

  const createList = async () => {
    if (!newListName.trim()) return toast.error('List name required');
    try {
      const { list } = await groceryAPI.create({ title: newListName, items: [] });
      setLists(p => [list, ...p]);
      setActiveList(list);
      setNewListName('');
      setShowNew(false);
      toast.success('Grocery list created!');
    } catch (err) { toast.error(err.message); }
  };

  const addItem = async () => {
    if (!newItem.name.trim()) return toast.error('Item name required');
    if (!activeList) return;
    try {
      const updated = { ...activeList, items: [...(activeList.items || []), newItem] };
      const { list } = await groceryAPI.update(activeList._id, { items: updated.items });
      setActiveList(list);
      setLists(p => p.map(l => l._id === list._id ? { ...l } : l));
      setNewItem({ name: '', amount: '', unit: '', category: 'Other' });
      setShowAddItem(false);
      toast.success('Item added!');
    } catch (err) { toast.error(err.message); }
  };

  const toggleItem = async (itemId) => {
    if (!activeList) return;
    try {
      const { list } = await groceryAPI.toggleItem(activeList._id, itemId);
      setActiveList(list);
    } catch {}
  };

  const removeItem = async (itemId) => {
    if (!activeList) return;
    const items = activeList.items.filter(i => i._id !== itemId);
    try {
      const { list } = await groceryAPI.update(activeList._id, { items });
      setActiveList(list);
    } catch {}
  };

  const deleteList = async (id) => {
    try {
      await groceryAPI.delete(id);
      setLists(p => p.filter(l => l._id !== id));
      if (activeList?._id === id) {
        const remaining = lists.filter(l => l._id !== id);
        setActiveList(remaining.length > 0 ? null : null);
        if (remaining.length > 0) loadList(remaining[0]._id);
        else setActiveList(null);
      }
      toast.success('List deleted');
    } catch (err) { toast.error(err.message); }
  };

  const exportPDF = () => {
    if (!activeList) return;
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(activeList.title, 20, 25);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Generated by RecipeIQ · ${new Date().toLocaleDateString()}`, 20, 32);

    const grouped = {};
    (activeList.items || []).forEach(item => {
      const cat = item.category || 'Other';
      if (!grouped[cat]) grouped[cat] = [];
      grouped[cat].push(item);
    });

    let y = 45;
    doc.setTextColor(0);
    Object.entries(grouped).forEach(([cat, items]) => {
      if (y > 260) { doc.addPage(); y = 20; }
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.text(cat, 20, y); y += 8;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      items.forEach(item => {
        if (y > 265) { doc.addPage(); y = 20; }
        const check = item.purchased ? '✓' : '☐';
        const qty = item.amount ? `${item.amount} ${item.unit || ''}`.trim() : '';
        doc.text(`  ${check}  ${item.name}${qty ? '  (' + qty + ')' : ''}`, 20, y);
        y += 7;
      });
      y += 4;
    });

    doc.save(`${activeList.title.replace(/\s+/g, '_')}_grocery.pdf`);
    toast.success('PDF exported!');
  };

  const purchasedCount = activeList?.items?.filter(i => i.purchased).length || 0;
  const totalCount = activeList?.items?.length || 0;
  const progress = totalCount > 0 ? (purchasedCount / totalCount) * 100 : 0;

  const groupedItems = {};
  (activeList?.items || []).forEach(item => {
    const cat = item.category || 'Other';
    if (!groupedItems[cat]) groupedItems[cat] = [];
    groupedItems[cat].push(item);
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-gray-900 dark:text-white flex items-center gap-2">
            <ShoppingCart className="w-6 h-6 text-green-500" /> Grocery Lists
          </h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">Manage your shopping lists</p>
        </div>
        <button onClick={() => setShowNew(true)} className="btn-primary flex items-center gap-2 text-sm self-start">
          <Plus className="w-4 h-4" /> New List
        </button>
      </div>

      {showNew && (
        <div className="card p-4 flex gap-3">
          <input value={newListName} onChange={e => setNewListName(e.target.value)} onKeyDown={e => e.key === 'Enter' && createList()} placeholder="List name..." className="input-field flex-1 py-2" />
          <button onClick={createList} className="btn-primary py-2 px-4 text-sm">Create</button>
          <button onClick={() => setShowNew(false)} className="btn-secondary py-2 px-3 text-sm"><X className="w-4 h-4" /></button>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* List sidebar */}
        <div className="space-y-2">
          <h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Your Lists</h2>
          {loading ? <div className="space-y-2">{[1,2,3].map(i => <div key={i} className="skeleton h-14 rounded-xl" />)}</div>
            : lists.length === 0 ? <p className="text-sm text-gray-400 card p-4 text-center">No lists yet</p>
            : lists.map(list => (
            <div key={list._id} onClick={() => loadList(list._id)}
              className={`card p-3.5 cursor-pointer transition-all ${activeList?._id === list._id ? 'border-primary-400 bg-primary-50 dark:bg-primary-900/20' : 'hover:border-gray-300'}`}>
              <div className="flex items-center justify-between">
                <p className="font-medium text-sm text-gray-900 dark:text-white truncate">{list.title}</p>
                <button onClick={e => { e.stopPropagation(); deleteList(list._id); }} className="p-1 hover:text-red-500 text-gray-400 flex-shrink-0">
                  <Trash2 className="w-3 h-3" />
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Active list */}
        <div className="lg:col-span-3">
          {activeList ? (
            <div className="card p-5 space-y-5">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-xl font-bold text-gray-900 dark:text-white">{activeList.title}</h2>
                  <p className="text-sm text-gray-500">{purchasedCount}/{totalCount} items purchased</p>
                </div>
                <div className="flex gap-2">
                  <button onClick={exportPDF} className="btn-secondary text-sm py-2 flex items-center gap-2">
                    <Download className="w-4 h-4" /> Export PDF
                  </button>
                  <button onClick={() => setShowAddItem(true)} className="btn-primary text-sm py-2 flex items-center gap-2">
                    <Plus className="w-4 h-4" /> Add Item
                  </button>
                </div>
              </div>

              {/* Progress */}
              {totalCount > 0 && (
                <div>
                  <div className="w-full bg-gray-100 dark:bg-gray-800 rounded-full h-2">
                    <div className="bg-green-500 h-2 rounded-full transition-all duration-500" style={{ width: `${progress}%` }} />
                  </div>
                  <p className="text-xs text-gray-400 mt-1">{progress.toFixed(0)}% complete</p>
                </div>
              )}

              {/* Add item form */}
              <AnimatePresence>
                {showAddItem && (
                  <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }}
                    className="bg-gray-50 dark:bg-gray-800 rounded-xl p-4 space-y-3">
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                      <input value={newItem.name} onChange={e => setNewItem(p => ({ ...p, name: e.target.value }))} placeholder="Item name *" className="input-field text-sm py-2 col-span-2" />
                      <input value={newItem.amount} onChange={e => setNewItem(p => ({ ...p, amount: e.target.value }))} placeholder="Amount" className="input-field text-sm py-2" />
                      <input value={newItem.unit} onChange={e => setNewItem(p => ({ ...p, unit: e.target.value }))} placeholder="Unit" className="input-field text-sm py-2" />
                    </div>
                    <div className="flex gap-3">
                      <select value={newItem.category} onChange={e => setNewItem(p => ({ ...p, category: e.target.value }))} className="input-field text-sm py-2 flex-1">
                        {CATEGORIES.map(c => <option key={c}>{c}</option>)}
                      </select>
                      <button onClick={addItem} className="btn-primary text-sm py-2 px-4">Add</button>
                      <button onClick={() => setShowAddItem(false)} className="btn-secondary text-sm py-2 px-3"><X className="w-4 h-4" /></button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Items grouped by category */}
              {Object.keys(groupedItems).length === 0 ? (
                <div className="text-center py-12">
                  <ShoppingCart className="w-12 h-12 text-gray-300 dark:text-gray-700 mx-auto mb-3" />
                  <p className="text-gray-500 text-sm">No items yet. Add some!</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {Object.entries(groupedItems).map(([cat, items]) => (
                    <div key={cat}>
                      <h3 className="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-2">{cat}</h3>
                      <div className="space-y-1.5">
                        {items.map(item => (
                          <div key={item._id} className={`flex items-center gap-3 p-3 rounded-xl border transition-all ${item.purchased ? 'bg-green-50 dark:bg-green-900/10 border-green-200 dark:border-green-800' : 'bg-white dark:bg-gray-800 border-gray-100 dark:border-gray-700'}`}>
                            <button onClick={() => toggleItem(item._id)} className={`w-5 h-5 rounded-full border-2 flex items-center justify-center flex-shrink-0 transition-all ${item.purchased ? 'bg-green-500 border-green-500' : 'border-gray-300 dark:border-gray-600 hover:border-green-400'}`}>
                              {item.purchased && <Check className="w-3 h-3 text-white" />}
                            </button>
                            <span className={`flex-1 text-sm ${item.purchased ? 'line-through text-gray-400' : 'text-gray-700 dark:text-gray-300'}`}>
                              {item.name}
                              {(item.amount || item.unit) && <span className="text-gray-400 ml-1">({item.amount} {item.unit})</span>}
                            </span>
                            <button onClick={() => removeItem(item._id)} className="p-1 hover:text-red-500 text-gray-400">
                              <X className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ) : (
            <div className="card p-12 flex flex-col items-center justify-center text-center">
              <ShoppingCart className="w-16 h-16 text-gray-300 dark:text-gray-700 mb-4" />
              <p className="text-gray-500 font-medium">Select or create a grocery list</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
